when:
  event: push

pipeline:
  lib:
    image: ghcr.io/ldproxy/golang-jdk:1.2
    commands:
      - cd xtracfg
      - CGO_CFLAGS="-I$JAVA_HOME/include -I$JAVA_HOME/include/linux" GOOS=linux GOARCH=amd64 go build -ldflags="-s -w '-extldflags=-z noexecstack'" -buildmode c-archive -o dist/libxtracfg.a
      - ls -la dist

  bin:
    image: ghcr.io/ldproxy/liberica-nik:22-jdk11
    commands:
      - cd xtracfg
      - ./gradlew nativeCompile
      - ls -la build/native/nativeCompile
