when:
  event: push

pipeline:
  lib:
    image: ghcr.io/ldproxy/golang-jdk:1.2
    commands:
      - cd xtracfg
      - CGO_CFLAGS="-I$JAVA_HOME/include -I$JAVA_HOME/include/linux" GOOS=linux GOARCH=amd64 go build -ldflags="-s -w '-extldflags=-z noexecstack'" -buildmode c-archive -o dist/libxtracfg.a
      - ls -la dist

  bin:
    image: ghcr.io/ldproxy/liberica-nik:22-jdk11
    commands:
      - cd xtracfg
      - ./gradlew nativeCompile
      - ls -la build/native/nativeCompile

  github:
    image: meltwaterfoundation/github-cli:2.29.0
    commands:
      - gh release create next --draft "xtracfg/build/native/nativeCompile/xtracfg#xtracfg (linux/amd64)"
    secrets: [ github_token ]
